#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x1A541148054E9E38 (infra-root@openstack.org)
#
Name     : pycadf
Version  : 2.9.0
Release  : 37
URL      : http://tarballs.openstack.org/pycadf/pycadf-2.9.0.tar.gz
Source0  : http://tarballs.openstack.org/pycadf/pycadf-2.9.0.tar.gz
Source99 : http://tarballs.openstack.org/pycadf/pycadf-2.9.0.tar.gz.asc
Summary  : CADF Library
Group    : Development/Tools
License  : Apache-2.0
Requires: pycadf-data = %{version}-%{release}
Requires: pycadf-license = %{version}-%{release}
Requires: pycadf-python = %{version}-%{release}
Requires: pycadf-python3 = %{version}-%{release}
Requires: debtcollector
Requires: oslo.config
Requires: oslo.serialization
Requires: pytz
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : pbr
Patch1: 0001-test.patch

%description
========================
Team and repository tags
========================
.. image:: https://governance.openstack.org/tc/badges/pycadf.svg
:target: https://governance.openstack.org/tc/reference/tags/index.html

%package data
Summary: data components for the pycadf package.
Group: Data

%description data
data components for the pycadf package.


%package license
Summary: license components for the pycadf package.
Group: Default

%description license
license components for the pycadf package.


%package python
Summary: python components for the pycadf package.
Group: Default
Requires: pycadf-python3 = %{version}-%{release}

%description python
python components for the pycadf package.


%package python3
Summary: python3 components for the pycadf package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pycadf package.


%prep
%setup -q -n pycadf-2.9.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549124592
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pycadf
cp LICENSE %{buildroot}/usr/share/package-licenses/pycadf/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## install_append content
install -d -m 755 %{buildroot}/usr/share/defaults/pycadf
mv %{buildroot}/usr/etc/pycadf/* %{buildroot}/usr/share/defaults/pycadf
rm -rf %{buildroot}/usr/etc
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/defaults/pycadf/ceilometer_api_audit_map.conf
/usr/share/defaults/pycadf/cinder_api_audit_map.conf
/usr/share/defaults/pycadf/glance_api_audit_map.conf
/usr/share/defaults/pycadf/neutron_api_audit_map.conf
/usr/share/defaults/pycadf/nova_api_audit_map.conf
/usr/share/defaults/pycadf/trove_api_audit_map.conf

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pycadf/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
