#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC12B8E73B30F2FC8 (infra-root@openstack.org)
#
Name     : pycadf
Version  : 3.1.0
Release  : 45
URL      : http://tarballs.openstack.org/pycadf/pycadf-3.1.0.tar.gz
Source0  : http://tarballs.openstack.org/pycadf/pycadf-3.1.0.tar.gz
Source1  : http://tarballs.openstack.org/pycadf/pycadf-3.1.0.tar.gz.asc
Summary  : CADF Library
Group    : Development/Tools
License  : Apache-2.0
Requires: pycadf-data = %{version}-%{release}
Requires: pycadf-license = %{version}-%{release}
Requires: pycadf-python = %{version}-%{release}
Requires: pycadf-python3 = %{version}-%{release}
Requires: debtcollector
Requires: oslo.config
Requires: oslo.serialization
Requires: pytz
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : debtcollector
BuildRequires : oslo.config
BuildRequires : oslo.serialization
BuildRequires : pbr
BuildRequires : pytz
BuildRequires : six
Patch1: 0001-test.patch

%description
PyCADF
        ======

%package data
Summary: data components for the pycadf package.
Group: Data

%description data
data components for the pycadf package.


%package license
Summary: license components for the pycadf package.
Group: Default

%description license
license components for the pycadf package.


%package python
Summary: python components for the pycadf package.
Group: Default
Requires: pycadf-python3 = %{version}-%{release}

%description python
python components for the pycadf package.


%package python3
Summary: python3 components for the pycadf package.
Group: Default
Requires: python3-core
Provides: pypi(pycadf)
Requires: pypi(debtcollector)
Requires: pypi(oslo.config)
Requires: pypi(oslo.serialization)
Requires: pypi(pytz)
Requires: pypi(six)

%description python3
python3 components for the pycadf package.


%prep
%setup -q -n pycadf-3.1.0
cd %{_builddir}/pycadf-3.1.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1594662640
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pycadf
cp %{_builddir}/pycadf-3.1.0/LICENSE %{buildroot}/usr/share/package-licenses/pycadf/b9a131284bb03c49a33f0ade435e87c1bff4394b
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## install_append content
install -d -m 755 %{buildroot}/usr/share/defaults/pycadf
mv %{buildroot}/usr/etc/pycadf/* %{buildroot}/usr/share/defaults/pycadf
rm -rf %{buildroot}/usr/etc
## install_append end

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/defaults/pycadf/ceilometer_api_audit_map.conf
/usr/share/defaults/pycadf/cinder_api_audit_map.conf
/usr/share/defaults/pycadf/glance_api_audit_map.conf
/usr/share/defaults/pycadf/neutron_api_audit_map.conf
/usr/share/defaults/pycadf/nova_api_audit_map.conf
/usr/share/defaults/pycadf/swift_api_audit_map.conf
/usr/share/defaults/pycadf/trove_api_audit_map.conf

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pycadf/b9a131284bb03c49a33f0ade435e87c1bff4394b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
